### ISSUE TITLE
Gameslists

### ISSUE THREAD

**Issue by XargonWan** [XargonWan/RetroQUEST#10]
# Description
Add a `gamelist/systemname.yml` (or `json`) file in the user data space where all the games are defined. 

# Acceptance criteria
- [ ] a gamelist can be generated for each system for example: `gamelist/megadrive.yml`
- [ ] the gamelists must contain each gameś relevant data
- [ ] the gamelists can be updated by the `scan_roms` function
- [ ] the gamelist can be updated from the `run_game` function such as `playtime` and `lastplayed`
- [ ] the gamelist can show if the game is favorited

# Notes
Example of a possible game list for the system `thissystem`:

`gamelist/thissystem.yml`
```yml
- filename: "this_game.ext"
  - name: "This game"
  - year: "1995"
  - description: "This game is pretty much a cool game"
  - label: "thisgame.png"
  - media: gb_gray
  - favorited: true
  - playcount: 5
  - lastplayed: 20241118T110633
```
